### ISSUE TITLE
Polytech

### ISSUE THREAD

**Issue by gagashaggy** [andreysidorovv/Auto-tests#2]
Отсутствует проверка, что текущий день недели выделен цветом. Кроме того, сейчас уже воскресенье, надо учитывать, что в этом случае ничего не должно быть выделено цветом

**Comment by andreysidorovv** [comment]
Исправил, засунул весь скрипт в **polytech-test.js**(исправленный с чеками по дате и чеком, что мы находимся на нужной странице). запустить скрипт в директории lab-2: npm test .\tests\polytech-tests.js
